spring:
  config:
    activate:
      on-profile: prod
    import: 'aws-parameterstore:'
 
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${database.chat.url}
    username: ${database.chat.user}
    password: ${database.chat.pass}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        color-codes: true
        type:
          descriptor:
            sql: trace
        default_batch_fetch_size: 100
      open-in-view: false

jwt:
  key: ${jwt.secret.key}

logging:
  level:
    org:
      springframework:
        web: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace